# Generated by Django 5.2.6 on 2025-11-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue_name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
    ]
